#!/bin/bash

if [ $# != 8 ]
then
	echo "Usage: run_hhblits <fasta_filename> <hhblits_bin_dir> <hhsuite_db_dir> <hhsuite_db_dir_2> <addss_bin_dir> <n_cpus> <output_dir> <multiple_alignment_filename>" >&2
	exit 1
fi

fasta_filename=$1
hhblits_bin_dir=$2
hhsuite_db_dir=$3
hhsuite_db_dir_2=$4
addss_bin_dir=$5
n_cpus=$6
output_dir=$7
multiple_alignment_filename=$8

hhmake_bin_dir=$hhblits_bin_dir

${hhblits_bin_dir}hhblits -i $fasta_filename -d ${hhsuite_db_dir}uniprot20_2016_02 -oa3m $multiple_alignment_filename -n 2 -cpu $n_cpus
${hhmake_bin_dir}hhmake -i $multiple_alignment_filename
perl ${addss_bin_dir}addss.pl $multiple_alignment_filename
${hhblits_bin_dir}hhblits -i $multiple_alignment_filename -d ${hhsuite_db_dir_2}pdb70 -n 1 -cpu $n_cpus

