#!/bin/bash

if [ $# -ne 15 ]
then
	echo "Usage: run_svm <data_dir> <scripts_dir> <libsvm_dir> <prediction_task> <n_classes> <dat_filename_psiblast> <dat_filename_hhmake> <average_postp_filename_psiblast> <average_postp_filename_hhmake> <average_distribution_3_filename> <pssm_window_size> <svm_input_data_filename> <svm_trained_model_filename> <libsvm_output_filename> <dspred_output_filename>"
	exit 1
fi

data_dir=$1
scripts_dir=$2
libsvm_dir=$3
prediction_task=$4
n_classes=$5
dat_filename_psiblast=$6
dat_filename_hhmake=$7
average_postp_filename_psiblast=$8
average_postp_filename_hhmake=$9
average_distribution_3_filename=${10}
pssm_window_size=${11}
svm_input_data_filename=${12}
svm_trained_model_filename=${13}
libsvm_output_filename=${14}
dspred_output_filename=${15}

python ${scripts_dir}generate_svm_input_data.py $dat_filename_psiblast $dat_filename_hhmake $average_postp_filename_psiblast $average_postp_filename_hhmake $average_distribution_3_filename $pssm_window_size $svm_input_data_filename

${libsvm_dir}svm-predict -b 1 $svm_input_data_filename $svm_trained_model_filename $libsvm_output_filename

python ${scripts_dir}reformat_svm_prediction_output.py $prediction_task $libsvm_output_filename $dspred_output_filename

echo $dspred_output_filename

